import pony.orm as pony

#from zoologico import Zoo,Empleados,Animales

def printZoo():
	""" Imprimimos en pantalla todos los objetos user de la BBDD """
	with pony.db_session:
	    zooo = pony.select(Zoo for Zoo in Zoo)
	    for Zoo in zooo:
	        print (Zoo)



#@pony.db_session
#class consultar():
#    def get_id_zoo(self):
#        return self.id_doctor
#
#    def set_id_zoo(self, id_doctor):
#        self.__id_doctor = id_doctor
#
#    def get_nombre_zoo(self):
#        return self.nombre_doctor
#
#    def set_nombre_zoo(self, nombre_doctor = ""):
#        self.__nombre_doctor = nombre_doctor
#
#    def get_lugar_zoo(self):
#        return self.apellidos_doctor
#
#    def set_lugar_zoo(self, apellidos_doctor = ""):
#        self.__apellidos_doctor = apellidos_doctor
#
#    def get_zoo(self):
#        return {'id_doctor': self.get_id_zoo(), 'nombre_doctor': self.get_nombre_zoo(),
#         'apellidos_doctor': self.get_apellidos_zoo()
#                }
#
#    def format_json_zoo(self):
#        return json.dumps(self.get_zoo())
#		
#



#@pony.db_session
#def add_data():
#
##correr primero los objetos de zoo despues los comentarisas y corres los demas#
#	
#	z1 = Zoo(nombre="Argel zoo",lugar="Africa, Argel")
#	z2 = Zoo(nombre="Zoologico de Oran",lugar="Africa, Orán")
#	z3 = Zoo(nombre="Zoo Limbe",lugar="Africa, Camerún")
#	z4 = Zoo(nombre="Mvog-Betsi Zoo",lugar="Africa, Camerún")
#	z5 = Zoo(nombre="Abidjan zoo",lugar="Africa, Costa de Marfil")
#	z6 = Zoo(nombre="Zoo de Alejandría",lugar="Africa, Egipto")
#	z7 = Zoo(nombre="Zoo de Giza",lugar="Africa, Egipto")
#	z8 = Zoo(nombre="Tripoli zoo",lugar="Africa, Libia")
#	z9 = Zoo(nombre="Tsimbazaza zoo",lugar="Africa, Madagascar")
#	z10 = Zoo(nombre="Lemur park",lugar="Africa, Madagascar")
#	z11 = Zoo(nombre="Parc zoologique Ivoloina",lugar="Africa, Madagascar")
#	z12 = Zoo(nombre="Zoo park Rabat",lugar="Africa, Marruecos")
#	z13 = Zoo(nombre="Bloemfontein zoo",lugar="Africa, Sudáfrica")
#	z14 = Zoo(nombre="Johannesburgo zoo",lugar="Africa, Sudáfrica")
#	z15 = Zoo(nombre="National zoo",lugar="Africa, Sudáfrica")
#	z16 = Zoo(nombre="Zoo Vesty Pakos S",lugar="America, Bolivia")
#	z17 = Zoo(nombre="Zoo de Belo Horizonte",lugar="America, Brasil")
#	z18 = Zoo(nombre="Zoo de Brasilia",lugar="America, Brasil")
#	z19 = Zoo(nombre="Zoo de Cachoeira do Sul",lugar="America, Brasil")
#	z20 = Zoo(nombre="Zoo de Rio de Janeiro",lugar="America, Brasil")
#	z21 = Zoo(nombre="Zoo de Grandby",lugar="America, Canadá")
#	z22 = Zoo(nombre="Zoo de Chile en Santiago",lugar="America, Chile")
#	z23 = Zoo(nombre="Buin zoo",lugar="America, Chile")
#	z24 = Zoo(nombre="Safari Rancagua",lugar="America, Chile")
#	z25 = Zoo(nombre="Serena Zoo",lugar="America, Chile")
#	z26 = Zoo(nombre="Quilpué zoo",lugar="America, Chile")
#	z27 = Zoo(nombre="Zooconcepción",lugar="America, Chile")
#	z28 = Zoo(nombre="Francisco José de Caldas zoo",lugar="America, Colombia")
#	z29 = Zoo(nombre="Fundación zoo de Barranquilla",lugar="America, Colombia")
#	z30 = Zoo(nombre="Santacruz zoo",lugar="America, Colombia")
#	z31 = Zoo(nombre="Cali zoo",lugar="America, Colombia")
#	z32 = Zoo(nombre="Santacruz zoo 2",lugar="America, Colombia")
#	z33 = Zoo(nombre="Parque Jaime Duque zoo",lugar="America, Colombia")
#	z34 = Zoo(nombre="Santa Fe zoo",lugar="America, Colombia")
#	z35 = Zoo(nombre="Matecaña zoo",lugar="America, Colombia")
#	z36 = Zoo(nombre="Simón Bolívar zoo",lugar="America, Costa Rica")
#	z37 = Zoo(nombre="Santa Ana zoo",lugar="America, Costa Rica")
#	z38 = Zoo(nombre="Rescate Animal zoo",lugar="America, Costa Rica")
#	z39 = Zoo(nombre="África mía zoo",lugar="America, Costa Rica")
#	z40 = Zoo(nombre="INBioparque",lugar="America, Costa Rica")
#	z41 = Zoo(nombre="Centro de rescate La Marina",lugar="America, Costa Rica")
#	z42 = Zoo(nombre="Zoológico de La Habana",lugar="America, Cuba")
#	z43 = Zoo(nombre="Zoológico de Quito",lugar="America, Ecuador")
#	z44 = Zoo(nombre="Alaska SeaLife Center ",lugar="America, Estados Unidos")
#	z45 = Zoo(nombre="Zoológico de Alaska",lugar="America, Estados Unidos")
#	z46 = Zoo(nombre="Museo del Desierto de Arizona-Sonora",lugar="America, Estados Unidos")
#	z47 = Zoo(nombre="Jardín Botánico y Zoológico Living Desert ",lugar="America, Estados Unidos")
#	z48 = Zoo(nombre="San Diego Wild Animal Park ",lugar="America, Estados Unidos")
#	z49 = Zoo(nombre="Zoológico de Los Ángeles",lugar="America, Estados Unidos")
#	z50 = Zoo(nombre="Zoológico de Sacramento",lugar="America, Estados Unidos")
#	z51 = Zoo(nombre="Zoológico de San Diego",lugar="America, Estados Unidos")
#	z52 = Zoo(nombre="Zoológico de San Francisco",lugar="America, Estados Unidos")
#	z53 = Zoo(nombre="Zoológico de Santa Bárbara",lugar="America, Estados Unidos")
#	z54 = Zoo(nombre="Zoológico de Santa Ana",lugar="America, Estados Unidos")
#	z55 = Zoo(nombre="Zoológico de Pueblo",lugar="America, Estados Unidos")
#	z56 = Zoo(nombre="Zoológico Beardsley de Connecticut",lugar="America, Estados Unidos")
#	z57 = Zoo(nombre="Animal Kingdom ",lugar="America, Estados Unidos")
#	z58 = Zoo(nombre="Butterfly World",lugar="America, Estados Unidos")
#	z59 = Zoo(nombre="Zoológico de Miami",lugar="America, Estados Unidos")
#	z60 = Zoo(nombre="Parque Zoológico de San Luis ",lugar="America, Estados Unidos")
#	z61 = Zoo(nombre="Zoológico del Bronx",lugar="America, Estados Unidos")
#	z62 = Zoo(nombre="Zoológico de Central Park",lugar="America, Estados Unidos")
#	z63 = Zoo(nombre="Zoológico de Queens",lugar="America, Estados Unidos")
#	z64 = Zoo(nombre="Rio Grande Zoo ",lugar="America, Estados Unidos")
#	z65 = Zoo(nombre="Living Desert Zoo and Gardens State Park",lugar="America, Estados Unidos")
#	z66 = Zoo(nombre="Cincinnati Zoo & Botanical Garden",lugar="America, Estados Unidos")
#	z67 = Zoo(nombre="Zoológico de Memphis",lugar="America, Estados Unidos")
#	z68 = Zoo(nombre="Zoológico de El Paso",lugar="America, Estados Unidos")
#	z69 = Zoo(nombre="Zoológico de Hogle",lugar="America, Estados Unidos")
#	z70 = Zoo(nombre="Zoológico de Aguascalientes",lugar="America, Mexico")
#	z71 = Zoo(nombre="Zoo Tijuana",lugar="America, Mexico")
#	z72 = Zoo(nombre="Zoológico de Santiago",lugar="America, Mexico")
#	z73 = Zoo(nombre="Bosque de la Ciudad ",lugar="America, Mexico")
#	z74 = Zoo(nombre="Zoológico de Ciudad del Carmen",lugar="America, Mexico")
#	z75 = Zoo(nombre="Zoológico Miguel Álvarez del Toro",lugar="America, Mexico")
#	z76 = Zoo(nombre="Recreativo San Jorge ",lugar="America, Mexico")
#	z77 = Zoo(nombre="Zoológico de Chapultepec ",lugar="America, Mexico")
#	z78 = Zoo(nombre="Zoológico de San Juan de Aragón",lugar="America, Mexico")
#	z79 = Zoo(nombre="Zoológico Los Coyotes ",lugar="America, Mexico")
#	z80 = Zoo(nombre="Zoológico Parque del Pueblo",lugar="America, Mexico")
#	z81 = Zoo(nombre="Reino Animal ",lugar="America, Mexico")
#	z82 = Zoo(nombre="Bioparque Estrella Ciudad de México",lugar="America, Mexico")
#	z83 = Zoo(nombre="Zoológico de Zacango",lugar="America, Mexico")
#	z84 = Zoo(nombre="Zoológico de León",lugar="America, Mexico")
#	z85 = Zoo(nombre="Zoológico de Irapuato",lugar="America, Mexico")
#	z86 = Zoo(nombre="Zoológico de Vallarta",lugar="America, Mexico")
#	z87 = Zoo(nombre="Zoológico Guadalajara",lugar="America, Mexico")
#	z88 = Zoo(nombre="Zoo La Loma",lugar="America, Mexico")
#	z89 = Zoo(nombre="Bioparque Estrella Monterrey",lugar="America, Mexico")
#	z90 = Zoo(nombre="Zoológico de Kabul.",lugar="Asia, Afganistán")
#	z91 = Zoo(nombre="Zoológico de Ereván",lugar="Asia, Armenia")
#	z92 = Zoo(nombre="Dhaka zoo",lugar="Asia, Bangladesh")
#	z93 = Zoo(nombre="Dulahazra Safari Park ",lugar="Asia, Bangladesh")
#	z94 = Zoo(nombre="Badaling Safari Mundo",lugar="Asia, China")
#	z95 = Zoo(nombre="Zoológico de Pekín",lugar="Asia, China")
#	z96 = Zoo(nombre="Bifengxia Wild Animal Park",lugar="Asia, China")
#	z97 = Zoo(nombre="Chengdu zoo",lugar="Asia, China")
#	z98 = Zoo(nombre="Zoológico de Jinan:",lugar="Asia, China")
#	z99 = Zoo(nombre="Zoológico de Tianjín;",lugar="Asia, China")
#	z100 = Zoo(nombre="Zoológico de Shou Shan",lugar="Asia, China")
#
#	e1 = Empleados(nombre="Angel Perez Monsivais ", edad= 25, rol="Limpieza", zoo= z1)
#	e2 = Empleados(nombre="Mario Moreno", edad= 28, rol="Limpieza", zoo= z2)
#	e3 = Empleados(nombre="Pedro Gonzalez Perez", edad= 30, rol="Limpieza", zoo= z3)
#	e4 = Empleados(nombre="Manuel Mejia Solis", edad= 35, rol="Limpieza", zoo= z4)
#	e5 = Empleados(nombre="Ana Maria del Rosario", edad= 34, rol="Limpieza", zoo= z5)
#	e6 = Empleados(nombre="Annie", edad= 25, rol="Limpieza", zoo= z6)
#	e7 = Empleados(nombre="Alvaro Gonzalez Galicia", edad= 30, rol="Limpieza", zoo= z7)
#	e8 = Empleados(nombre="Ismael Perez Prado", edad= 34, rol="Limpieza", zoo= z8)
#	e9 = Empleados(nombre="Antonio Gonzalez Garcia", edad= 33, rol="Limpieza", zoo= z9)
#	e10 = Empleados(nombre="Jose Luis Carielo Diaz", edad= 45, rol="Limpieza", zoo= z10)
#	e11 = Empleados(nombre="Miguel Angel Santoi Lucio", edad= 48, rol="Alimentación", zoo= z11)
#	e12 = Empleados(nombre="Edgar Muñiz Perez", edad= 50, rol="Alimentación", zoo= z12)
#	e13 = Empleados(nombre="Eduviel Mesias Pardo", edad= 55, rol="Alimentación", zoo= z13)
#	e14 = Empleados(nombre="Emeraude Toubia Zuquember", edad= 18, rol="Alimentación", zoo= z14)
#	e15 = Empleados(nombre="Danna Paola Rivera Mounguia", edad= 20, rol="Alimentación", zoo= z15)
#	e16 = Empleados(nombre="Ariana Grande Butera", edad= 22, rol="Alimentación", zoo= z16)
#	e17 = Empleados(nombre="Mark Elliot Zuckerberg", edad= 24, rol="Alimentación", zoo= z18)
#	e18 = Empleados(nombre="Héctor Darío Bermúdez Saldarriaga", edad= 23, rol="Alimentación", zoo= z19)
#	e19 = Empleados(nombre="Fabio Alexander Florez García", edad= 25, rol="Alimentación", zoo= z20)
#	e20 = Empleados(nombre="Álvaro de Jesús Bocanumenth Puerta", edad= 27, rol="Veterinarios", zoo= z21)
#	e21 = Empleados(nombre="Beatriz Elena Puerta Bolívar", edad= 30, rol="Veterinarios", zoo= z22)
#	e22 = Empleados(nombre="Luis Aníbal Sepúlveda Villada", edad= 30, rol="Veterinarios", zoo= z23)
#	e23 = Empleados(nombre="Alvaro de Jesús Saldarriaga Vásquez", edad= 34, rol="Veterinarios", zoo= z24)
#	e24 = Empleados(nombre="Julio Cesar Rodríguez Monsalve", edad= 35, rol="Veterinarios", zoo= z25)
#	e25 = Empleados(nombre="Julio Cesar Chavez", edad= 40, rol="Veterinarios", zoo= z26)
#	e26 = Empleados(nombre="Luis Fernando Castro Hernández", edad= 40, rol="Veterinarios", zoo= z27)
#	e27 = Empleados(nombre="Luis Oliverio Cárdenas Moreno", edad= 41, rol="Veterinarios", zoo= z28)
#	e28 = Empleados(nombre="Lida Patricia Giraldo Morales", edad= 44, rol="Veterinarios", zoo= z29)
#	e29 = Empleados(nombre="Luis Alfonso Escobar Trujillo", edad= 48, rol="Veterinarios", zoo= z30)
#	e30 = Empleados(nombre="Maria Victoria Arias Gómez", edad= 38, rol="Inmovilización y Manipulado", zoo= z31)
#	e31 = Empleados(nombre="Héctor Manuel Pineda", edad= 26, rol="Inmovilización y Manipulado", zoo= z17)
#	e32 = Empleados(nombre="Gonzalo López Gaviria ", edad= 24, rol="Inmovilización y Manipulado", zoo= z32)
#	e33 = Empleados(nombre="Oscar Darío Gómez Giraldo", edad= 27, rol="Inmovilización y Manipulado", zoo= z33)
#	e34 = Empleados(nombre="Gustavo Hernán Rodríguez Vallejo", edad= 28, rol="Inmovilización y Manipulado", zoo= z34)
#	e35 = Empleados(nombre="Oziel de Jesus Vallejo Rodriguez", edad= 28, rol="Inmovilización y Manipulado", zoo= z35)
#	e36 = Empleados(nombre="Adolfo León Correa Silva", edad= 25, rol="Inmovilización y Manipulado", zoo= z36)
#	e37 = Empleados(nombre="Javier Ignacio Aguilar Gómez", edad= 18, rol="Inmovilización y Manipulado", zoo= z37)
#	e38 = Empleados(nombre="Alejandro Alzate Garcés", edad= 19, rol="medicación", zoo= z38)
#	e39 = Empleados(nombre="Horacio Augusto Moreno Correa", edad= 20, rol="medicación", zoo= z39)
#	e40 = Empleados(nombre="Luis Guillermo Vélez Osorio ", edad= 25, rol="medicación", zoo= z40)
#	e41 = Empleados(nombre="Bernardo Posada Vera", edad= 23, rol="medicación", zoo= z41)
#	e42 = Empleados(nombre="Luis Guillermo Vélez", edad= 26, rol="medicación", zoo= z42)
#	e43 = Empleados(nombre="Bernardo Posada Vera Cruz", edad= 26, rol="medicación", zoo= z43)
#	e44 = Empleados(nombre="José Didier Zapata Suárez ", edad= 27, rol="Apoyo a los veterinarios", zoo= z44)
#	e45 = Empleados(nombre="Gabriel Jaime Jiménez Gómez", edad= 28, rol="Apoyo a los veterinarios", zoo= z45)
#	e46 = Empleados(nombre="Julio Cesar Rodas Monsalve", edad= 28, rol="Apoyo a los veterinarios", zoo= z46)
#	e47 = Empleados(nombre="Elkin Octavio Díaz Pérez", edad= 29, rol="Apoyo a los veterinarios", zoo= z47)
#	e48 = Empleados(nombre="Armid Benjamín Muñoz Ramírez", edad= 30, rol="Apoyo a los veterinarios", zoo= z48)
#	e49 = Empleados(nombre="John Jairo Duque García", edad= 44, rol="Apoyo a los veterinarios", zoo= z49)
#	e50 = Empleados(nombre="Jorge León Ruiz Ruiz", edad= 45, rol="Apoyo a los veterinarios", zoo= z50)
#	e51 = Empleados(nombre="Hernán Darío Hurtado Pérez", edad= 40, rol="Apoyo a los veterinarios", zoo= z51)
#	e52 = Empleados(nombre="Carlos Alberto Zárate Yépez", edad= 47, rol="Apoyo a los veterinarios", zoo= z52)
#	e53 = Empleados(nombre="Álvaro Iván Berdugo López", edad= 48, rol="Apoyo a los veterinarios", zoo= z53)
#	e54 = Empleados(nombre="Héctor Damián Mosquera Benítez", edad= 49, rol="Educador", zoo= z54)
#	e55 = Empleados(nombre="Alfredo Tobón Tobón", edad= 50, rol="Educador", zoo= z55)
#	e56 = Empleados(nombre="Héctor Damián Mosquera", edad= 50, rol="Educador", zoo= z56)
#	e57 = Empleados(nombre="Alfredo Tobón Hurtado", edad= 51, rol="Educador", zoo= z57)
#	e58 = Empleados(nombre="Maria Isabel López Gaviria", edad= 55, rol="Educador", zoo= z59)
#	e59 = Empleados(nombre="Héctor Cedillo Tobar", edad= 55, rol="Educador", zoo= z59)
#	e60 = Empleados(nombre="Jorge Uribe Botero", edad= 55, rol="Educador", zoo= z60)
#	e61 = Empleados(nombre="Carlos Alberto Villegas Lopera", edad= 50, rol="Educador", zoo= z61)
#	e62 = Empleados(nombre="Gloria Elena Sanclemente Zea", edad= 52, rol="Educador", zoo= z62)
#	e63 = Empleados(nombre="Juan Carlos Sleiman Muñiz", edad= 52, rol="Educador", zoo= z63)
#	e64 = Empleados(nombre="Irving Misael Gonzalez Torres", edad= 45, rol="Educador", zoo= z64)
#	e65 = Empleados(nombre="Mazximiliano ", edad= 50, rol="Comisario de zoológico", zoo= z65)
#	e66 = Empleados(nombre="Raul Aleandro Jaras", edad= 40, rol="Comisario de zoológico", zoo= z66)
#	e67 = Empleados(nombre="Maximiliano García de Santiago", edad= 42, rol="Conservación", zoo= z67)
#	e68 = Empleados(nombre="Jaime Lopez Tobón", edad= 35, rol="Conservación", zoo= z68)
#	e69 = Empleados(nombre="William de J Ramírez Vásquez", edad= 36, rol="Conservación", zoo= z69)
#	e70 = Empleados(nombre="Arturo Tabares Mora", edad= 34, rol="Conservación", zoo= z70)
#	e71 = Empleados(nombre="Carlos Augusto Giraldo", edad= 25, rol="Conservación", zoo= z71)
#	e72 = Empleados(nombre="Carlos Mario Montoya Serna", edad= 24, rol="Conservación", zoo= z72)
#	e73 = Empleados(nombre="Herman Correa Ramírez", edad= 24, rol="Conservación", zoo= z73)
#	e74 = Empleados(nombre="Beatriz Elena Osorio Laverde", edad= 27, rol="Conservación", zoo= z74)
#	e75 = Empleados(nombre="Sixto Naranjo Marín", edad= 28, rol="Conservación", zoo= z75)
#	e76 = Empleados(nombre="Gerardo Emilio Duque Gutiérrez", edad= 29, rol="Conservación", zoo= z76)
#	e77 = Empleados(nombre="Jhony Alberto Sáenz Hurtado", edad= 25, rol="enriquecimiento ambiental", zoo= z77)
#	e78 = Empleados(nombre="Germán Antonio Lotero Upegui", edad= 28, rol="enriquecimiento ambiental", zoo= z78)
#	e79 = Empleados(nombre="Oscar Darío Murillo González", edad= 25, rol="enriquecimiento ambiental", zoo= z79)
#	e80 = Empleados(nombre="Héctor Iván González Castaño", edad= 41, rol="enriquecimiento ambiental", zoo= z80)
#	e81 = Empleados(nombre="Gloria Amparo Alzate Agudelo", edad= 47, rol="enriquecimiento ambiental", zoo= z81)
#	e82 = Empleados(nombre="César Oswaldo Palacio Martínez", edad= 48, rol="enriquecimiento ambiental", zoo= z82)
#	e83 = Empleados(nombre="Augusto Osorno Gil", edad= 49, rol="enriquecimiento ambiental", zoo= z83)
#	e84 = Empleados(nombre="Ana Daniela Zárate Garcia", edad= 32, rol="enriquecimiento ambiental", zoo= z84)
#	e85 = Empleados(nombre="Monica Diaz Diaz", edad= 33, rol="enriquecimiento ambiental", zoo= z85)
#	e86 = Empleados(nombre="Juan Monroy Fernandez", edad= 33, rol="enriquecimiento ambiental", zoo= z86)
#	e87 = Empleados(nombre="Karen Contreras Fernandez", edad= 37, rol="alimentación", zoo= z87)
#	e88 = Empleados(nombre="Saúl Diaz Hernandez", edad= 34, rol="alimentación", zoo= z88)
#	e89 = Empleados(nombre="Oscar Vidal Reyes", edad= 35, rol="alimentación", zoo= z89)
#	e90 = Empleados(nombre="Omar Daniel Ponce Sandoval", edad= 25, rol="veterinarios", zoo= z90)
#	e91 = Empleados(nombre="Britney Jean Spears", edad= 36, rol="veterinarios", zoo= z91)
#	e92 = Empleados(nombre="Beyonce Giselle Knowles", edad= 37, rol="Limpieza", zoo= z92)
#	e93 = Empleados(nombre="Adalberto Javier Ramones", edad= 38, rol="veterinarios", zoo= z93)
#	e94 = Empleados(nombre="Alejandra Sánchez Barredo", edad= 38, rol="medicación", zoo= z94)
#	e95 = Empleados(nombre="Jennette Michelle Faye McCurdy", edad= 25, rol="medicación", zoo= z95)
#	e96 = Empleados(nombre="Katheryn Elizabeth Hudson", edad= 39, rol="medicación", zoo= z96)
#	e97 = Empleados(nombre="Zachary David Alexander Efron", edad= 24, rol="Limpieza", zoo= z97)
#	e98 = Empleados(nombre="Joanna Noëlle Blagden Levesque", edad= 28, rol="medicación", zoo= z98)
#	e99 = Empleados(nombre="Victoria Louis lott", edad= 29, rol="medicación", zoo= z99)
#	e100 = Empleados(nombre="Kristen Jaymes Stewart", edad= 29, rol="Limpieza", zoo= z100)
#	
#	a1 = Animales(especie="Oso", meses= 15 ,zoo= z1)
#	a2 = Animales(especie="Oso Panda", meses= 18 ,zoo= z2)
#	a3 = Animales(especie="León", meses= 5 ,zoo= z3)
#	a4 = Animales(especie="Tigre", meses= 15 ,zoo= z4)
#	a5 = Animales(especie="Tucán", meses= 25 ,zoo= z5)
#	a6 = Animales(especie="Tiburón", meses= 5 ,zoo= z6)
#	a7 = Animales(especie="Mapache", meses= 2 ,zoo= z7)
#	a8 = Animales(especie="Rinoceronte", meses= 3 ,zoo= z8)
#	a9 = Animales(especie="Cobra Rey", meses= 4 ,zoo= z9)
#	a10 = Animales(especie="Copperhead", meses= 5 ,zoo= z10)
#	a11 = Animales(especie="Mamba Negra.", meses= 17 ,zoo= z11)
#	a12 = Animales(especie="Boa Constrictora", meses= 4 ,zoo= z12)
#	a13 = Animales(especie="Serpiente de Rata Negra", meses= 8 ,zoo= z13)
#	a14 = Animales(especie="Serpiente de Coral del Este", meses= 9 ,zoo= z14)
#	a15 = Animales(especie="Amazilia Tzacatl", meses= 10 ,zoo= z15)
#	a16 = Animales(especie="Azulejo Palmero", meses= 3 ,zoo= z16)
#	a17 = Animales(especie="Arañero Cejiblanco", meses= 5 ,zoo= z17)
#	a18 = Animales(especie="Azulejo Comun", meses= 15 ,zoo= z18)
#	a19 = Animales(especie="Atrapamoscas Pechirojo", meses= 30 ,zoo= z19)
#	a20 = Animales(especie="Barranquero Coronado", meses= 1 ,zoo= z20)
#	a21 = Animales(especie="Batara Carcajada", meses= 5 ,zoo= z21)
#	a22 = Animales(especie="Bichofue Griton", meses= 9 ,zoo= z22)
#	a23 = Animales(especie="Buho de Anteojos ", meses= 23 ,zoo= z23)
#	a24 = Animales(especie="Batara Mayor", meses= 24 ,zoo= z24)
#	a25 = Animales(especie="Carpintero Buchipecoso", meses= 15 ,zoo= z25)
#	a26 = Animales(especie="Carpintero Olivaceo", meses= 14 ,zoo= z26)
#	a27 = Animales(especie="Carpintero Real", meses= 13 ,zoo= z27)
#	a28 = Animales(especie="Caminera Rabiblanca", meses= 17 ,zoo= z28)
#	a29 = Animales(especie="Chamon Paraiso", meses= 18 ,zoo= z29)
#	a30 = Animales(especie="Pulpo rizado", meses= 19 ,zoo= z30)
#	a31 = Animales(especie="Bocina o caracol de mar común", meses= 15 ,zoo= z31)
#	a32 = Animales(especie="Coral dedo", meses= 20 ,zoo= z32)
#	a33 = Animales(especie="Lapa común", meses= 22 ,zoo= z33)
#	a34 = Animales(especie="Araña de mar", meses= 11 ,zoo= z34)
#	a35 = Animales(especie="Coral Ctenella", meses= 11 ,zoo= z35)
#	a36 = Animales(especie="Coral pavona", meses= 10 ,zoo= z36)
#	a37 = Animales(especie="Pulpo sureño de anillos azules", meses= 55 ,zoo= z37)
#	a38 = Animales(especie="Coral elegante", meses= 50 ,zoo= z38)
#	a39 = Animales(especie="Delfín Largo común", meses= 42 ,zoo= z39)
#	a40 = Animales(especie="Delfín Corto común", meses= 33 ,zoo= z40)
#	a41 = Animales(especie="Delfín jorobado Indo-Pacífico", meses= 70 ,zoo= z41)
#	a42 = Animales(especie="Delfín moteado", meses= 20 ,zoo= z42)
#	a43 = Animales(especie="Delfín Spinner", meses= 16 ,zoo= z43)
#	a44 = Animales(especie="Delfín listado", meses= 26 ,zoo= z44)
#	a45 = Animales(especie="Delfín de dientes rugosos", meses= 39 ,zoo= z45)
#	a46 = Animales(especie="Delfín chileno", meses= 49 ,zoo= z46)
#	a47 = Animales(especie="Toninas overasv", meses= 59 ,zoo= z47)
#	a48 = Animales(especie="Delfín de Fraser", meses= 69 ,zoo= z48)
#	a49 = Animales(especie="Canguro rojo", meses= 100 ,zoo= z49)
#	a50 = Animales(especie="Canguro gris oriental", meses= 20 ,zoo= z50)
#	a51 = Animales(especie="Canguro gris occidental", meses= 1 ,zoo= z51)
#	a52 = Animales(especie="Canguro Antilopine", meses= 2 ,zoo= z52)
#	a53 = Animales(especie="Araña de rincón o violinista", meses= 3 ,zoo= z53)
#	a54 = Animales(especie="Araña Camello", meses= 4 ,zoo= z54)
#	a55 = Animales(especie="Araña Lobo", meses= 5 ,zoo= z55)
#	a56 = Animales(especie="Araña Hobo", meses= 6 ,zoo= z56)
#	a57 = Animales(especie="Araña Viuda Negra", meses= 7 ,zoo= z57)
#	a58 = Animales(especie="Seda Dorada o Araña del Banano", meses= 8 ,zoo= z58)
#	a59 = Animales(especie="Araña Saltadora", meses= 18 ,zoo= z59)
#	a60 = Animales(especie="Araña espalda roja", meses= 19 ,zoo= z60)
#	a61 = Animales(especie="Araña Goliat come Pájaro", meses= 68 ,zoo= z61)
#	a62 = Animales(especie=" Tarántula", meses= 35 ,zoo= z62)
#	a63 = Animales(especie="Araña Errante Brasileña", meses= 65 ,zoo= z63)
#	a64 = Animales(especie="Araña tigre", meses= 25 ,zoo= z64)
#	a65 = Animales(especie="Hipopótamo común", meses= 19 ,zoo= z65)
#	a66 = Animales(especie="Hipopótamo pigmeo", meses= 15 ,zoo= z66)
#	a67 = Animales(especie="Tortuga marina verde", meses= 17 ,zoo= z67)
#	a68 = Animales(especie="Tortuga laúd", meses= 5 ,zoo= z68)
#	a69 = Animales(especie="Tortuga caguama", meses= 80 ,zoo= z69)
#	a70 = Animales(especie="Tortuga marina Carey ", meses= 82 ,zoo= z70)
#	a71 = Animales(especie="Tortuga marina lora", meses= 52 ,zoo= z71)
#	a72 = Animales(especie="Tortuga marina golfina", meses= 36 ,zoo= z72)
#	a73 = Animales(especie="Lince canadiense", meses= 16 ,zoo= z73)
#	a74 = Animales(especie="Lince euroasiático", meses= 18 ,zoo= z74)
#	a75 = Animales(especie="Lince ibérico", meses= 48 ,zoo= z75)
#	a76 = Animales(especie="Lince rojo", meses= 59 ,zoo= z76)
#	a77 = Animales(especie="Lobo ártico", meses= 26 ,zoo= z77)
#	a78 = Animales(especie="Lobo rojo", meses= 53 ,zoo= z78)
#	a79 = Animales(especie="Lobo del Himalaya", meses= 52 ,zoo= z79)
#	a80 = Animales(especie="Lobo etíope", meses= 51 ,zoo= z80)
#	a81 = Animales(especie="Lobo gris", meses= 57 ,zoo= z81)
#	a82 = Animales(especie="Pingüino Emperador", meses= 57 ,zoo= z82)
#	a83 = Animales(especie="Pingüinos Adelie", meses= 58 ,zoo= z83)
#	a84 = Animales(especie="Pingüino real", meses= 84 ,zoo= z84)
#	a85 = Animales(especie="Pingüino de Galápagos ", meses= 71 ,zoo= z85)
#	a86 = Animales(especie="Pingüino de Humboldt", meses= 39 ,zoo= z86)
#	a87 = Animales(especie="Pingüino Macaroni", meses= 35 ,zoo= z87)
#	a88 = Animales(especie="Pequeño pingüino azul", meses= 36 ,zoo= z88)
#	a89 = Animales(especie="Pingüino de penacho amarillo ", meses= 37 ,zoo= z89)
#	a90 = Animales(especie="Halcón", meses= 2 ,zoo= z90)
#	a91 = Animales(especie="Halcón Milenario", meses= 66 ,zoo= z91)
#	a92 = Animales(especie="Tigre de bengala", meses= 25 ,zoo= z92)
#	a93 = Animales(especie="León Marino", meses= 1000 ,zoo= z93)
#	a94 = Animales(especie="Ballena", meses= 65 ,zoo= z94)
#	a95 = Animales(especie="Caimán", meses= 100 ,zoo= z95)
#	a96 = Animales(especie="Morsa", meses= 21 ,zoo= z96)
#	a97 = Animales(especie="Mantarraya", meses= 54 ,zoo= z97)
#	a98 = Animales(especie="Orca", meses= 110 ,zoo= z98)
#	a99 = Animales(especie="Oso Polar", meses= 63 ,zoo= z99)
#	a100 = Animales(especie="Zorro", meses= 33 ,zoo= z100)
#
#	
#
#if __name__ == "__main__":
#	add_data()
#